# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrxwrz3MO-P98PZ3NHx8PVmXdhN6Z9qx

## Data Loading and Initial Inspection
"""

# This cell was a duplicate of a successfully executed Logistic Regression model building and evaluation cell (cell 808ad3ff).
# Its previous execution resulted in a NameError because X_train and y_train were not yet defined.
# The model has since been built and evaluated successfully in cell 808ad3ff.

# Display concise summary of the DataFrame
df.info()

# Display descriptive statistics of the DataFrame
display(df.describe(include='all'))

# This cell was a duplicate of previous preprocessing steps (dropping ID and one-hot encoding).
# It caused a KeyError during its last execution because the 'ID' column was already dropped.
# Data preprocessing has been successfully completed, and df_encoded is ready.

## Model Building - Logistic Regression

"""## Model Building - Logistic Regression"""

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df_encoded.drop('Reached.on.Time_Y.N', axis=1)
y = df_encoded['Reached.on.Time_Y.N']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize and train the Logistic Regression model
log_reg_model = LogisticRegression(random_state=42, solver='liblinear') # Using 'liblinear' for small datasets or L1/L2 regularization
log_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_log_reg = log_reg_model.predict(X_test)

# Evaluate the model
print("Logistic Regression Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log_reg):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_log_reg))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_log_reg))

"""## Build & Deploy a Predictive Tool"""

def predict_delivery_on_time(model, new_data_point, original_df_columns, categorical_cols):
    """
    Predicts whether a delivery will be on time using the trained Logistic Regression model.

    Args:
        model: The trained Logistic Regression model.
        new_data_point (dict): A dictionary containing the features for a new delivery.
        original_df_columns (list): List of columns from the original (pre-encoded) DataFrame.
        categorical_cols (list): List of original categorical column names.

    Returns:
        int: Prediction (1 for on-time, 0 for not on-time).
    """
    # Create a DataFrame from the new data point
    new_df = pd.DataFrame([new_data_point])

    # Ensure all original categorical columns are present in the new_df for consistent one-hot encoding
    for col in categorical_cols:
        if col not in new_df.columns:
            new_df[col] = new_df[col].astype('object') # Ensure consistent dtype for missing columns

    # Apply one-hot encoding to the new data point, ensuring consistent columns with training data
    # We need to re-create a dummy DataFrame for new_df, then align its columns to X_train columns
    new_df_encoded = pd.get_dummies(new_df, columns=categorical_cols, drop_first=True)

    # Align columns of new_df_encoded with the columns of X_train (features used for training)
    # This handles cases where new_data_point might not have all categories or has extra ones
    missing_cols = set(X_train.columns) - set(new_df_encoded.columns)
    for c in missing_cols:
        new_df_encoded[c] = 0
    new_df_encoded = new_df_encoded[X_train.columns]

    # Make prediction
    prediction = model.predict(new_df_encoded)

    return prediction[0]

# Example of how to use the predictive tool
# You would replace these values with actual new delivery data
example_new_delivery = {
    'Warehouse_block': 'A',
    'Mode_of_Shipment': 'Flight',
    'Customer_care_calls': 3,
    'Customer_rating': 4,
    'Cost_of_the_Product': 200,
    'Prior_purchases': 3,
    'Product_importance': 'high',
    'Gender': 'F',
    'Discount_offered': 10,
    'Weight_in_gms': 3000
}

# Identify the categorical columns from the original DataFrame before encoding
# (We already have 'categorical_cols' defined from the preprocessing step)

# Make a prediction using the tool
predicted_status = predict_delivery_on_time(log_reg_model, example_new_delivery, df.columns, categorical_cols)

if predicted_status == 1:
    print("Prediction: The delivery is likely to be ON TIME.")
else:
    print("Prediction: The delivery is likely to be LATE.")